package org.example.mirimilibe.notification.domain;

public enum NotificationType {
    NOTICE_NEW,
    QUESTION_NEW_ANSWER,
    QUESTION_ANOTHER_ANSWER,
    QUESTION_FIRST_LIKE,
    QUESTION_MILESTONE_LIKE,
    ANSWER_FIRST_LIKE,
    ANSWER_MILESTONE_LIKE,
    QUESTION_HOT_SELECTED,
    ANSWER_BEST_SELECTED,
    DAILY_HOT_QUESTION,
    DAILY_WAITING_ANSWER,
	DAILY_QUESTION_REMINDER

}